### ISSUE TITLE
Add dweb.link to publicsuffix.org

### ISSUE THREAD

**Issue by lidel** [ipfs/infra#476]
> _Parent issues:_ https://github.com/ipfs/ipfs/issues/337, https://github.com/ipfs/in-web-browsers/issues/89 
> _cc_ https://github.com/ipfs/infra/issues/391, https://github.com/ipfs/infra/issues/81, https://github.com/ipfs/go-ipfs/issues/5982, https://github.com/ipfs-shipyard/ipfs-companion/issues/527, @mburns, @lgierth, @Stebalien 

## Context

As noted in https://github.com/ipfs/infra/issues/81, we will be setting up  cid-in-subdomain proxying at `<cidv1b32>.ipfs.dweb.link`

I believe getting it right means adding it to The Public Suffix List ([publicsuffix.org](https://publicsuffix.org)), to ensure websites loaded via dweb.link gateway can't interfere with each other's cookies.

## Proposal

Changes I want to submit in a PR to [publicsuffix/list](https://github.com/publicsuffix/list) are in [lidel/list#dweb.link](https://github.com/publicsuffix/list/compare/master...lidel:dweb.link) branch:

> ###  Add public suffix entries for dweb.link 
>
> Anyone can effectively create the following subdomains by adding content to IPFS:
> 
>   *.ipfs.dweb.link (eg: bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq.ipfs.dweb.link)
> 
> Other protocols will be supported in the future, for example:
> 
>   *.dat.dweb.link (eg: 778f8d955175c92e4ced5e4f5563f69bfec0c86cc6f670352c457943666fe639.dat.dweb.link)
> 
> To ensure websites loaded via dweb.link gateway can't interfere with each other's cookies,
> I suggest adding the following public suffix record:
> 
> *.dweb.link

## Tasks

Based on https://github.com/publicsuffix/list/wiki/Guidelines#submitting-amendments I've split this endeavor into small subtasks:

- [x] Fork [publicsuffix/list](https://github.com/publicsuffix/list) and add suffix for `*.dweb.link`
- [x] Someone from infra team reviews [proposed change to publicsuffix.org](https://github.com/publicsuffix/list/compare/master...lidel:dweb.link) and confirms `noc@` email listed there is valid for this use (just add comment in this issue).
  > [..] make sure that the email you listed in the pull request is valid, as we may use it for validation or private follow ups.
- [ ] We need to make `http://<cidv1b32>.ipfs.dweb.link` work ([this](http://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq.ipfs.dweb.link) should return wikipedia, right now returns 404):
  > When submitting private domains, provide expected input/output to help us validate the correctness of the request
- [x] PR against [publicsuffix/list](https://github.com/publicsuffix/list) and writes down the PR number
  - Done in https://github.com/publicsuffix/list/pull/766
- [x] Infra team adds DNS TXT record to authorize the PR number created in the previous step ([details](https://github.com/publicsuffix/list/wiki/Guidelines#private-domains))
     ```
     $ dig TXT _psl.dweb.link
     https://github.com/publicsuffix/list/pull/<TBD>
     ```
- [x] update the PR marking it ready for review and we wait for it to be approved

**Comment by mburns** [comment]
I've actually got this ball rolling already: https://github.com/publicsuffix/list/pull/766

Happy to tweak my implementation to match yours (apex + subdomains vs your use of wildcard)

**Comment by lidel** [comment]
@mburns :man_facepalming:  I probably made a typo in search and that is why I did not found already existing PR – sorry! 
I am closing this in favour of https://github.com/ipfs/infra/issues/83#issuecomment-460615452

ps. If we swap subdomains with wildcard it will save us another PR when we want to add a gateway for `dat` – but its up to you :)
