### ISSUE TITLE
Deprecate the SoLarnet bootstrappers

### ISSUE THREAD

**Issue by mburns** [ipfs/infra#496]
fixes https://github.com/protocol/bifrost-infra/issues/680 , connected to https://github.com/ipfs/go-ipfs/issues/6797

The IPFS Infra team is retiring the "SoLarnet" boxen, those machines tarting with `QmSoL...` peerids, that are used to join (bootstrap) into the IPFS network. They are being replaced by 4 shiny, new `bootstrap.libp2p.io` machines, that we have precomputed and put in the default bootstrap list years ago (thanks, ghosts of infra past!)

Going forward, these addresses should be relied on:

```
/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN
/dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa
/dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb
/dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt
```

We hard code these `QmSoL` addresses in a lot of places. I took a swipe at updating some of them:

- [x] https://github.com/ipfs/js-ipfs/pull/2581
- [x] https://github.com/libp2p/js-libp2p-bootstrap/pull/98
- [ ] https://github.com/libp2p/js-libp2p/pull/554
- [x] https://github.com/ipfs/js-datastore-level/pull/27
- [x] https://github.com/ipfs/js-ipfs-unixfs-importer/pull/53

# TODO
- [x] talk with lead devs, make sure the change is understood.
- [ ] write up an announcement https://github.com/ipfs/infra/issues/378#issuecomment-584476786
- [x] doc updates CC @jessicaschilling (?)

**Comment by Stebalien** [comment]
Stop.

We can't do this _unless_ we get rid of the recursive dnsaddr resolution.  At the moment, reaching those new nodes depends on recursively resolving dns addrs and we only added support for that in go-ipfs 0.4.23.

I'm also not sure what the state of js-ipfs/js-libp2p is.

**Comment by olizilla** [comment]
We're not going to turn any solarnet boxen off. We'll let 0.5 get out the door, then we'll remove the solarnet entries from the defaults, then wait a good few releases before turning them off.

**Comment by mburns** [comment]
it has been a good few releases.

The SoLarnet boxen were quietly retired last week due to their legacy key size (https://github.com/protocol/bifrost-infra/issues/1118). Thanks to @gmas @aschmahmann @marten-seemann & @jacobheun for coordinating this.
